# Generated by Django 4.2.21 on 2025-05-18 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_date', models.DateField(verbose_name='Ngày chi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('expense_type', models.CharField(choices=[('rent', 'Tiền thuê'), ('salary', 'Lương'), ('utilities', 'Tiện ích'), ('equipment', 'Thiết bị'), ('maintenance', 'Bảo trì'), ('marketing', 'Tiếp thị'), ('other', 'Khác')], max_length=20, verbose_name='Loại chi phí')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='expenses/', verbose_name='Ảnh biên lai')),
            ],
            options={
                'verbose_name': 'Chi phí',
                'verbose_name_plural': 'Chi phí',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Số hóa đơn')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số tiền')),
                ('payment_date', models.DateTimeField(verbose_name='Ngày thanh toán')),
                ('payment_method', models.CharField(choices=[('cash', 'Tiền mặt'), ('credit_card', 'Thẻ tín dụng'), ('bank_transfer', 'Chuyển khoản'), ('e_wallet', 'Ví điện tử')], max_length=20, verbose_name='Phương thức thanh toán')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ'), ('completed', 'Hoàn thành'), ('failed', 'Thất bại'), ('refunded', 'Hoàn tiền')], default='pending', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='Ảnh biên lai')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.membership', verbose_name='Gói thành viên')),
            ],
            options={
                'verbose_name': 'Thanh toán',
                'verbose_name_plural': 'Thanh toán',
                'ordering': ['-payment_date'],
            },
        ),
    ]
