# Generated by Django 4.2.21 on 2025-05-18 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classtypeprice_class_format'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AddField(
            model_name='payment',
            name='bonus_sessions',
            field=models.PositiveIntegerField(default=0, verbose_name='Số buổi tặng thêm'),
        ),
        migrations.AddField(
            model_name='payment',
            name='class_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classtypeprice', verbose_name='Gói lớp học'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percent', 'Giảm theo %'), ('amount', 'Giảm số tiền')], max_length=10, null=True, verbose_name='Loại khuyến mãi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Giá trị khuyến mãi'),
        ),
        migrations.AddField(
            model_name='payment',
            name='final_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Số tiền thanh toán'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng tiền'),
        ),
    ]
