# Generated by Django 4.2.21 on 2025-05-18 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_classtypeprice_class_format'),
        ('payments', '0002_alter_payment_options_payment_bonus_sessions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='membership',
        ),
        migrations.AddField(
            model_name='payment',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classtype', verbose_name='Loại lớp học'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='class_price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classtypeprice', verbose_name='Gói buổi học'),
        ),
    ]
