# Generated by Django 4.2.21 on 2025-05-21 16:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_attendance_customer_package_and_more'),
        ('customers', '0010_customerpackage'),
        ('payments', '0003_remove_payment_membership_payment_class_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date', '-created_at'], 'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_type',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='receipt_image',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='bonus_sessions',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='class_price',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='final_amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='receipt_image',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Tiền thuê'), ('salary', 'Lương nhân viên'), ('utility', 'Tiện ích'), ('maintenance', 'Bảo trì'), ('inventory', 'Nhập kho'), ('marketing', 'Marketing'), ('other', 'Khác')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='expense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='paid_by',
            field=models.CharField(default='Admin', max_length=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='payment',
            name='paid_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Số tiền đã thanh toán (chỉ áp dụng cho thanh toán một phần)', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='payment_proofs/'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('full', 'Thanh toán toàn bộ'), ('partial', 'Thanh toán một phần')], default='full', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='Số tiền còn lại cần thanh toán', max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='remaining_payment_due_date',
            field=models.DateField(blank=True, help_text='Ngày đến hạn thanh toán số tiền còn lại', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='class_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='classes.classtype'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount_type',
            field=models.CharField(choices=[('none', 'Không áp dụng'), ('percentage', 'Giảm theo %'), ('amount', 'Giảm theo số tiền')], default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Tiền mặt'), ('bank_transfer', 'Chuyển khoản'), ('card', 'Thẻ'), ('other', 'Khác')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Đã hoàn thành'), ('pending', 'Chờ xử lý'), ('cancelled', 'Đã hủy')], default='completed', max_length=20),
        ),
    ]
