# Generated by Django 4.2.21 on 2025-05-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_alter_instructor_sunday_hourly_rate_and_more'),
        ('payments', '0004_alter_payment_options_remove_expense_expense_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_payments', to='instructors.instructor', verbose_name='Người bán hàng (HLV)'),
        ),
    ]
