# Generated by Django 4.2.21 on 2025-05-23 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_merge_20250518_2120'),
        ('payments', '0005_payment_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='branches.branch', verbose_name='Chi nhánh'),
        ),
    ]
