# Generated by Django 4.2.21 on 2025-05-18 10:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instructors', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Thứ 2'), (1, 'Thứ 3'), (2, 'Thứ 4'), (3, 'Thứ 5'), (4, 'Thứ 6'), (5, 'Thứ 7'), (6, 'Chủ nhật')], verbose_name='Ngày trong tuần')),
                ('start_time', models.TimeField(verbose_name='Giờ bắt đầu')),
                ('end_time', models.TimeField(verbose_name='Giờ kết thúc')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('room', models.CharField(max_length=50, verbose_name='Phòng')),
            ],
            options={
                'verbose_name': 'Lịch học',
                'verbose_name_plural': 'Lịch học',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='ClassType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên loại lớp')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('duration', models.PositiveIntegerField(verbose_name='Thời lượng (phút)')),
                ('max_capacity', models.PositiveIntegerField(verbose_name='Sức chứa tối đa')),
                ('difficulty_level', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Mức độ khó (1-5)')),
            ],
            options={
                'verbose_name': 'Loại lớp học',
                'verbose_name_plural': 'Loại lớp học',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên gói thành viên')),
                ('description', models.TextField(verbose_name='Mô tả')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Thời hạn (ngày)')),
                ('classes_allowed', models.PositiveIntegerField(verbose_name='Số buổi được phép')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá')),
                ('active', models.BooleanField(default=True, verbose_name='Còn hiệu lực')),
            ],
            options={
                'verbose_name': 'Loại thành viên',
                'verbose_name_plural': 'Loại thành viên',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(verbose_name='Ngày kết thúc')),
                ('classes_remaining', models.PositiveIntegerField(verbose_name='Số buổi còn lại')),
                ('status', models.CharField(choices=[('active', 'Đang hoạt động'), ('expired', 'Hết hạn'), ('cancelled', 'Đã hủy'), ('on_hold', 'Tạm dừng')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng')),
                ('membership_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.membershiptype', verbose_name='Loại thành viên')),
            ],
            options={
                'verbose_name': 'Thành viên',
                'verbose_name_plural': 'Thành viên',
            },
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Ngày')),
                ('actual_start_time', models.TimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu thực tế')),
                ('actual_end_time', models.TimeField(blank=True, null=True, verbose_name='Thời gian kết thúc thực tế')),
                ('status', models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', max_length=20, verbose_name='Trạng thái')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('class_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classschedule', verbose_name='Lịch học')),
            ],
            options={
                'verbose_name': 'Buổi học',
                'verbose_name_plural': 'Buổi học',
                'ordering': ['-date', 'class_schedule__start_time'],
            },
        ),
        migrations.AddField(
            model_name='classschedule',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classtype', verbose_name='Loại lớp'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor', verbose_name='Huấn luyện viên'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=False, verbose_name='Đã tham dự')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name='Giờ vào')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Giờ ra')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classsession', verbose_name='Buổi học')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Điểm danh',
                'verbose_name_plural': 'Điểm danh',
                'unique_together': {('class_session', 'customer')},
            },
        ),
    ]
