# Generated by Django 4.2.21 on 2025-05-18 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_remove_branch_amenities_and_more'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtype',
            name='branches',
            field=models.ManyToManyField(related_name='class_types', to='branches.branch', verbose_name='Chi nhánh áp dụng'),
        ),
        migrations.AlterField(
            model_name='classtype',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả'),
        ),
        migrations.CreateModel(
            name='ClassTypePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_format', models.CharField(choices=[('pt', 'PT (Cá nhân)'), ('group_1', 'Nhóm 1 người'), ('group_2', 'Nhóm 2 người'), ('group_3', 'Nhóm 3 người')], max_length=20, verbose_name='Hình thức lớp')),
                ('number_of_sessions', models.PositiveIntegerField(verbose_name='Số buổi')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='classes.classtype', verbose_name='Loại lớp')),
            ],
            options={
                'verbose_name': 'Bảng giá lớp học',
                'verbose_name_plural': 'Bảng giá lớp học',
                'ordering': ['class_format', 'number_of_sessions'],
                'unique_together': {('class_type', 'class_format', 'number_of_sessions')},
            },
        ),
    ]
