# Generated by Django 4.2.21 on 2025-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_classtype_branches_alter_classtype_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtypeprice',
            name='class_format',
            field=models.CharField(choices=[('pt_1_1', 'PT 1-1'), ('group_1_3', 'Nhóm 1-3')], max_length=20, verbose_name='Hình thức lớp'),
        ),
    ]
