# Generated by Django 4.2.21 on 2025-05-19 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_delete_membership_delete_membershiptype'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='end_date',
            field=models.DateField(blank=True, help_text='Để trống nếu lặp lại vô hạn', null=True, verbose_name='Ngày kết thúc'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Lặp lại hàng tuần'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='recurring_days',
            field=models.JSONField(blank=True, help_text='Danh sách các ngày trong tuần lặp lại (0: Thứ 2, 1: Thứ 3, ...)', null=True, verbose_name='Các ngày lặp lại'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày bắt đầu'),
        ),
        migrations.AddField(
            model_name='classtype',
            name='class_category',
            field=models.CharField(choices=[('fixed', 'Lớp cố định'), ('registration', 'Lớp đăng ký'), ('trial', 'Lớp tập thử')], default='registration', max_length=20, verbose_name='Loại lớp'),
        ),
    ]
