# Generated by Django 4.2.21 on 2025-05-19 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0005_classschedule_end_date_classschedule_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classschedule',
            options={'ordering': ['specific_date', 'day_of_week', 'start_time'], 'verbose_name': 'Lịch học', 'verbose_name_plural': 'Lịch học'},
        ),
        migrations.AddField(
            model_name='classschedule',
            name='actual_end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Thời gian kết thúc thực tế'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='actual_start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Thời gian bắt đầu thực tế'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Ghi chú'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='parent_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_schedules', to='classes.classschedule', verbose_name='Lịch học gốc'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày cụ thể'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Đã lên lịch'), ('ongoing', 'Đang diễn ra'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='scheduled', help_text='Chỉ áp dụng cho buổi học cụ thể', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classschedule', verbose_name='Buổi học'),
        ),
        migrations.DeleteModel(
            name='ClassSession',
        ),
    ]
