# Generated by Django 4.2.21 on 2025-05-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_customerpackage'),
        ('classes', '0006_alter_classschedule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='customer_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customerpackage', verbose_name='Gói tập sử dụng'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='is_session_deducted',
            field=models.BooleanField(default=False, verbose_name='Đã trừ buổi tập'),
        ),
    ]
