# Generated by Django 4.2.21 on 2025-05-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0009_alter_classtypeprice_options_classtypeprice_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtypeprice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
