# Generated by Django 4.2.21 on 2025-05-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên tiện ích')),
                ('category', models.CharField(choices=[('general', 'Chung'), ('parking', 'Bãi đỗ xe và Di chuyển'), ('others', 'Khác')], max_length=20, verbose_name='Danh mục')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Biểu tượng')),
            ],
            options={
                'verbose_name': 'Tiện ích',
                'verbose_name_plural': 'Tiện ích',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên chi nhánh')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Số điện thoại')),
                ('google_map_url', models.URLField(blank=True, null=True, verbose_name='Địa chỉ Google Map')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/', verbose_name='Hình ảnh')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
                ('amenities', models.ManyToManyField(blank=True, related_name='branches', to='branches.amenity', verbose_name='Tiện ích')),
            ],
            options={
                'verbose_name': 'Chi nhánh',
                'verbose_name_plural': 'Chi nhánh',
                'ordering': ['name'],
            },
        ),
    ]
