# Generated by Django 4.2.21 on 2025-05-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_add_initial_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='amenities',
        ),
        migrations.AddField(
            model_name='branch',
            name='has_accessible_parking',
            field=models.BooleanField(default=False, verbose_name='Bãi đỗ xe cho người khuyết tật'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_bike_racks',
            field=models.BooleanField(default=False, verbose_name='Giá để xe đạp'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_childcare',
            field=models.BooleanField(default=False, verbose_name='Dịch vụ trông trẻ'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_elevator',
            field=models.BooleanField(default=False, verbose_name='Thang máy'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_food_drink',
            field=models.BooleanField(default=False, verbose_name='Đồ ăn/thức uống'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_gender_neutral_restroom',
            field=models.BooleanField(default=False, verbose_name='Nhà vệ sinh không phân biệt giới tính'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_lockers',
            field=models.BooleanField(default=False, verbose_name='Tủ khóa'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_parking',
            field=models.BooleanField(default=False, verbose_name='Bãi đỗ xe'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_shower',
            field=models.BooleanField(default=False, verbose_name='Phòng tắm'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_towel_service',
            field=models.BooleanField(default=False, verbose_name='Dịch vụ khăn tắm'),
        ),
        migrations.AddField(
            model_name='branch',
            name='has_wifi',
            field=models.BooleanField(default=False, verbose_name='Wifi'),
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
