# Generated by Django 4.2.21 on 2025-05-18 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0002_initial_amenities'),
        ('branches', '0003_remove_branch_amenities_and_more'),
    ]

    operations = [
    ]
