# Generated by Django 4.2.21 on 2025-05-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Tiểu sử')),
                ('certifications', models.TextField(blank=True, null=True, verbose_name='Chứng chỉ')),
                ('specialties', models.CharField(blank=True, max_length=255, null=True, verbose_name='Chuyên môn')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='instructors/', verbose_name='Ảnh đại diện')),
                ('hire_date', models.DateField(verbose_name='Ngày thuê')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Mức lương theo giờ')),
                ('active', models.BooleanField(default=True, verbose_name='Đang làm việc')),
            ],
            options={
                'verbose_name': 'Huấn luyện viên',
                'verbose_name_plural': 'Huấn luyện viên',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
