# Generated by Django 4.2.21 on 2025-05-23 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_update_instructor_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='email',
        ),
    ]
