# Generated by Django 4.2.21 on 2025-05-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0003_remove_instructor_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='sunday_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mức lương theo giờ (Chủ nhật)'),
        ),
        migrations.AlterField(
            model_name='instructor',
            name='weekday_hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Mức lương theo giờ (Thứ 2-7)'),
        ),
    ]
