# Generated by Django 4.2.21 on 2025-05-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Tên')),
                ('last_name', models.CharField(max_length=50, verbose_name='Họ')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Số điện thoại')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Địa chỉ')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gender', models.CharField(choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1, verbose_name='Giới tính')),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='Liên hệ khẩn cấp')),
                ('health_issues', models.TextField(blank=True, null=True, verbose_name='Vấn đề sức khỏe')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='customers/', verbose_name='Ảnh đại diện')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('active', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Khách hàng',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
