# Generated by Django 4.2.21 on 2025-05-18 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['full_name'], 'verbose_name': 'Khách hàng', 'verbose_name_plural': 'Khách hàng'},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Họ và tên bố/mẹ (nếu có)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại bố/mẹ'),
        ),
        migrations.AddField(
            model_name='customer',
            name='source',
            field=models.CharField(choices=[('referral', 'Giới thiệu'), ('fanpage', 'Fanpage'), ('google_map', 'Google map'), ('direct', 'Trực tiếp'), ('social_media', 'Social media'), ('other', 'Kênh khác')], default='direct', max_length=20, verbose_name='Nguồn khách hàng'),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('contact', 'Liên hệ'), ('trial', 'Tập thử'), ('purchased', 'Mua gói'), ('repurchased', 'Tái mua')], default='contact', max_length=20, verbose_name='Trạng thái khách hàng'),
        ),
        migrations.CreateModel(
            name='HealthDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='health_documents/', verbose_name='Tài liệu sức khỏe')),
                ('document_type', models.CharField(choices=[('image', 'Hình ảnh'), ('pdf', 'PDF')], max_length=10, verbose_name='Loại tài liệu')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tải lên')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_documents', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Tài liệu sức khỏe',
                'verbose_name_plural': 'Tài liệu sức khỏe',
            },
        ),
    ]
