# Generated by Django 4.2.21 on 2025-05-18 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_full_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung liên hệ')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian liên hệ')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='customers.customer', verbose_name='Khách hàng')),
            ],
            options={
                'verbose_name': 'Hoạt động khách hàng',
                'verbose_name_plural': 'Hoạt động khách hàng',
                'ordering': ['-timestamp'],
            },
        ),
    ]
