# Generated by Django 4.2.21 on 2025-05-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_customeractivity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('contact', 'Liên hệ'), ('trial', 'Tập thử'), ('purchased', 'Mua gói'), ('repurchased', 'Tái mua'), ('no_trial', 'Không đến tập thử'), ('no_purchase', 'Không mua'), ('no_repurchase', 'Không tái mua')], default='contact', max_length=20, verbose_name='Trạng thái khách hàng'),
        ),
    ]
