# Generated by Django 4.2.21 on 2025-05-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdocument',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Mô tả tình trạng'),
        ),
    ]
