# Generated by Django 4.2.21 on 2025-05-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Nội dung cuộc hẹn'),
        ),
    ]
