# Generated by Django 4.2.21 on 2025-05-19 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_classschedule_options_and_more'),
        ('payments', '0003_remove_payment_membership_payment_class_type_and_more'),
        ('customers', '0009_alter_appointment_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_sessions', models.PositiveIntegerField(verbose_name='Tổng số buổi')),
                ('remaining_sessions', models.PositiveIntegerField(verbose_name='Số buổi còn lại')),
                ('start_date', models.DateField(verbose_name='Ngày bắt đầu')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ngày kết thúc')),
                ('status', models.CharField(choices=[('active', 'Đang sử dụng'), ('pending', 'Chờ kích hoạt'), ('expired', 'Hết hạn'), ('used_up', 'Đã dùng hết buổi'), ('cancelled', 'Đã hủy')], default='active', max_length=20, verbose_name='Trạng thái')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Ngày mua')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classtype', verbose_name='Loại lớp')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='customers.customer', verbose_name='Khách hàng')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_package', to='payments.payment', verbose_name='Đơn hàng')),
            ],
            options={
                'verbose_name': 'Gói tập',
                'verbose_name_plural': 'Gói tập',
                'ordering': ['-purchase_date', 'status'],
            },
        ),
    ]
