# Generated by Django 4.2.21 on 2025-05-22 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_attendance_customer_package_and_more'),
        ('payments', '0004_alter_payment_options_remove_expense_expense_type_and_more'),
        ('customers', '0010_customerpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdocument',
            name='related_attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_documents', to='classes.attendance', verbose_name='Buổi tập liên quan'),
        ),
        migrations.AddField(
            model_name='healthdocument',
            name='related_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_documents', to='payments.payment', verbose_name='Thanh toán liên quan'),
        ),
        migrations.AlterField(
            model_name='healthdocument',
            name='document_type',
            field=models.CharField(choices=[('image', 'Hình ảnh'), ('pdf', 'PDF'), ('video', 'Video'), ('other', 'Khác')], max_length=10, verbose_name='Loại tài liệu'),
        ),
    ]
