# Generated by Django 4.2.21 on 2025-05-22 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_healthdocument_related_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='customers.customer', verbose_name='Bố/mẹ'),
        ),
    ]
